export const countriesOpt = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Congo, Republic of the',
  'Congo, Democratic Republic of the',
  'Costa Rica',
  "Cote d'Ivoire",
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Fiji',
  'Finland',
  'France',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Grenada',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Kosovo',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'North Korea',
  'North Macedonia',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Palestine',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  'Romania',
  'Russia',
  'Rwanda',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Korea',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Vatican City',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Zambia',
  'Zimbabwe',
];

export const businessTypeOpt = [
  'Accounting',
  'Advertising',
  'Aerospace',
  'Agriculture',
  'Artificial Intelligence',
  'Automotive',
  'Beauty',
  'Biotechnology',
  'Catering',
  'Cleaning Services',
  'Cloud Computing',
  'Construction',
  'Consulting',
  'Cybersecurity',
  'Data Analytics',
  'E-commerce',
  'Education',
  'Entertainment',
  'Environmental Services',
  'Event Planning',
  'Fashion and Apparel',
  'Financial Services',
  'Food and Beverage Production',
  'Graphic Design',
  'Gym',
  'Healthcare',
  'Hospitality',
  'Insurance',
  'Interior Design',
  'Internet of Things (IoT)',
  'IT Software',
  'Landscaping',
  'Legal Services',
  'Logistics',
  'Manufacturing',
  'Marketing',
  'Mobile App Development',
  'Pharmaceuticals',
  'Photography',
  'Real Estate',
  'Renewable Energy',
  'Repair Services',
  'Restaurant',
  'Retail',
  'Robotics',
  'Telecommunications',
  'Tourism',
  'Transportation',
  'Web Development',
  'Wellness',
];

export const educationTypesOpt = [
  'Public College',
  'Private College',
  'Trade School',
  'Vocational Training',
  'Online Education',
  'Apprenticeship',
  'High School',
  'Homeschooling',
  'Tutoring',
  'Language Courses',
  'Skill Development Courses',
  'Professional Certifications',
];

export const currencyOpt = [
  { title: 'Algerian Dinar (دج)', value: 'DZD' },
  { title: 'Angolan Kwanza (Kz)', value: 'AOA' },
  { title: 'Argentine Peso ($)', value: 'ARS' },
  { title: 'Armenian Dram (֏)', value: 'AMD' },
  { title: 'Australian Dollar ($)', value: 'AUD' },
  { title: 'Azerbaijani Manat (₼)', value: 'AZN' },
  { title: 'Bahamian Dollar ($)', value: 'BSD' },
  { title: 'Bahraini Dinar (.د.ب)', value: 'BHD' },
  { title: 'Bangladeshi Taka (৳)', value: 'BDT' },
  { title: 'Barbadian Dollar ($)', value: 'BBD' },
  { title: 'Belarusian Ruble (Br)', value: 'BYN' },
  { title: 'Belize Dollar ($)', value: 'BZD' },
  { title: 'Bermudian Dollar ($)', value: 'BMD' },
  { title: 'Bhutanese Ngultrum (Nu.)', value: 'BTN' },
  { title: 'Bolivian Boliviano (Bs.)', value: 'BOB' },
  { title: 'Botswana Pula (P)', value: 'BWP' },
  { title: 'Brazilian Real (R$)', value: 'BRL' },
  { title: 'Brunei Dollar ($)', value: 'BND' },
  { title: 'Bulgarian Lev (Лв.)', value: 'BGN' },
  { title: 'Burundian Franc (FBu)', value: 'BIF' },
  { title: 'Cambodian Riel (៛)', value: 'KHR' },
  { title: 'Canadian Dollar ($)', value: 'CAD' },
  { title: 'Cape Verdean Escudo ($)', value: 'CVE' },
  { title: 'Cayman Islands Dollar ($)', value: 'KYD' },
  { title: 'Central African CFA Franc (Fr)', value: 'XAF' },
  { title: 'Chilean Peso ($)', value: 'CLP' },
  { title: 'Chinese Yuan (¥)', value: 'CNY' },
  { title: 'Colombian Peso ($)', value: 'COP' },
  { title: 'Comorian Franc (CF)', value: 'KMF' },
  { title: 'Congolese Franc (FC)', value: 'CDF' },
  { title: 'Costa Rican Colón (₡)', value: 'CRC' },
  { title: 'Croatian Kuna (kn)', value: 'HRK' },
  { title: 'Cuban Peso (₱)', value: 'CUP' },
  { title: 'Czech Koruna (Kč)', value: 'CZK' },
  { title: 'Cypriot Pound (£)', value: 'CYP' },
  { title: 'Danish Krone (kr)', value: 'DKK' },
  { title: 'Djiboutian Franc (Fdj)', value: 'DJF' },
  { title: 'Dominican Peso (RD$)', value: 'DOP' },
  { title: 'East Caribbean Dollar ($)', value: 'XCD' },
  { title: 'Egyptian Pound (£)', value: 'EGP' },
  { title: 'Eritrean Nakfa (ናቕፋ)', value: 'ERN' },
  { title: 'Ethiopian Birr (Br)', value: 'ETB' },
  { title: 'Euro (€)', value: 'EUR' },
  { title: 'Falkland Islands Pound (£)', value: 'FKP' },
  { title: 'Fijian Dollar ($)', value: 'FJD' },
  { title: 'Gambian Dalasi (D)', value: 'GMD' },
  { title: 'Georgian Lari (ლ)', value: 'GEL' },
  { title: 'Ghanaian Cedi (₵)', value: 'GHS' },
  { title: 'Gibraltar Pound (£)', value: 'GIP' },
  { title: 'Guatemalan Quetzal (Q)', value: 'GTQ' },
  { title: 'Guernsey Pound (£)', value: 'GGP' },
  { title: 'Guinean Franc (FG)', value: 'GNF' },
  { title: 'Guyanese Dollar ($)', value: 'GYD' },
  { title: 'Haitian Gourde (G)', value: 'HTG' },
  { title: 'Honduran Lempira (L)', value: 'HNL' },
  { title: 'Hong Kong Dollar ($)', value: 'HKD' },
  { title: 'Hungarian Forint (Ft)', value: 'HUF' },
  { title: 'Icelandic Krona (kr)', value: 'ISK' },
  { title: 'Indian Rupee (₹)', value: 'INR' },
  { title: 'Indonesian Rupiah (Rp)', value: 'IDR' },
  { title: 'Iranian Rial (﷼)', value: 'IRR' },
  { title: 'Iraqi Dinar (ع.د)', value: 'IQD' },
  { title: 'Israeli Shekel (₪)', value: 'ILS' },
  { title: 'Jamaican Dollar ($)', value: 'JMD' },
  { title: 'Japanese Yen (¥)', value: 'JPY' },
  { title: 'Jersey Pound (£)', value: 'JEP' },
  { title: 'Jordanian Dinar (د.ا)', value: 'JOD' },
  { title: 'Kazakhstani Tenge (₸)', value: 'KZT' },
  { title: 'Kenyan Shilling (Ksh)', value: 'KES' },
  { title: 'Kuwaiti Dinar (د.ك)', value: 'KWD' },
  { title: 'Kyrgyzstani Som (сом)', value: 'KGS' },
  { title: 'Lao Kip (₭)', value: 'LAK' },
  { title: 'Lebanese Pound (ل.ل)', value: 'LBP' },
  { title: 'Lesotho Loti (L)', value: 'LSL' },
  { title: 'Liberian Dollar ($)', value: 'LRD' },
  { title: 'Libyan Dinar (ل.د)', value: 'LYD' },
  { title: 'Macanese Pataca (MOP$)', value: 'MOP' },
  { title: 'Macedonian Denar (ден)', value: 'MKD' },
  { title: 'Malagasy Ariary (Ar)', value: 'MGA' },
  { title: 'Malawian Kwacha (MK)', value: 'MWK' },
  { title: 'Malaysian Ringgit (RM)', value: 'MYR' },
  { title: 'Maldivian Rufiyaa (.ރ)', value: 'MVR' },
  { title: 'Manx Pound (£)', value: 'IMP' },
  { title: 'Mauritanian Ouguiya (UM)', value: 'MRU' },
  { title: 'Mauritian Rupee (₨)', value: 'MUR' },
  { title: 'Mexican Peso ($)', value: 'MXN' },
  { title: 'Moldovan Leu (L)', value: 'MDL' },
  { title: 'Mongolian Tögrög (₮)', value: 'MNT' },
  { title: 'Moroccan Dirham (ر.م.)', value: 'MAD' },
  { title: 'Mozambican Metical (MT)', value: 'MZN' },
  { title: 'Myanmar Kyat (Ks)', value: 'MMK' },
  { title: 'Namibian Dollar ($)', value: 'NAD' },
  { title: 'Nepalese Rupee (रू)', value: 'NPR' },
  { title: 'New Taiwan Dollar (NT$)', value: 'TWD' },
  { title: 'New Zealand Dollar ($)', value: 'NZD' },
  { title: 'Nicaraguan Córdoba (C$)', value: 'NIO' },
  { title: 'Nigerian Naira (₦)', value: 'NGN' },
  { title: 'North Korean Won (₩)', value: 'KPW' },
  { title: 'Norwegian Krone (kr)', value: 'NOK' },
  { title: 'Omani Rial (ر.ع.)', value: 'OMR' },
  { title: 'Pakistani Rupee (Rs)', value: 'PKR' },
  { title: 'Panamanian Balboa (B/.)', value: 'PAB' },
  { title: 'Papua New Guinean Kina (K)', value: 'PGK' },
  { title: 'Paraguayan Guaraní (₲)', value: 'PYG' },
  { title: 'Peruvian Sol (S/.)', value: 'PEN' },
  { title: 'Philippine Peso (₱)', value: 'PHP' },
  { title: 'Polish Zloty (zł)', value: 'PLN' },
  { title: 'Pound Sterling (£)', value: 'GBP' },
  { title: 'Qatari Riyal (ر.ق)', value: 'QAR' },
  { title: 'Romanian Leu (L)', value: 'RON' },
  { title: 'Russian Ruble (₽)', value: 'RUB' },
  { title: 'Rwandan Franc (FRw)', value: 'RWF' },
  { title: 'Samoan Tālā (WS$)', value: 'WST' },
  { title: 'São Tomé and Príncipe Dobra (Db)', value: 'STN' },
  { title: 'Saudi Riyal (﷼)', value: 'SAR' },
  { title: 'Seychellois Rupee (SR)', value: 'SCR' },
  { title: 'Sierra Leonean Leone (Le)', value: 'SLL' },
  { title: 'Singapore Dollar ($)', value: 'SGD' },
  { title: 'Solomon Islands Dollar ($)', value: 'SBD' },
  { title: 'Somali Shilling (Sh)', value: 'SOS' },
  { title: 'South African Rand (R)', value: 'ZAR' },
  { title: 'South Korean Won (₩)', value: 'KRW' },
  { title: 'Sri Lankan Rupee (Rs)', value: 'LKR' },
  { title: 'Sudanese Pound (ج.س.)', value: 'SDG' },
  { title: 'Surinamese Dollar ($)', value: 'SRD' },
  { title: 'Swazi Lilangeni (E)', value: 'SZL' },
  { title: 'Swedish Krona (kr)', value: 'SEK' },
  { title: 'Swiss Franc (Fr.)', value: 'CHF' },
  { title: 'Syrian Pound (LS)', value: 'SYP' },
  { title: 'Tajikistani Somoni (ЅМ)', value: 'TJS' },
  { title: 'Tanzanian Shilling (TSh)', value: 'TZS' },
  { title: 'Thai Baht (฿)', value: 'THB' },
  { title: 'Tongan Paʻanga (T$)', value: 'TOP' },
  { title: 'Trinidad and Tobago Dollar ($)', value: 'TTD' },
  { title: 'Tunisian Dinar (ت.د)', value: 'TND' },
  { title: 'Turkish Lira (₺)', value: 'TRY' },
  { title: 'Turkmenistan Manat (m)', value: 'TMT' },
  { title: 'Ugandan Shilling (USh)', value: 'UGX' },
  { title: 'Ukrainian Hryvnia (₴)', value: 'UAH' },
  { title: 'United Arab Emirates Dirham (د.إ)', value: 'AED' },
  { title: 'United States Dollar ($)', value: 'USD' },
  { title: 'Uruguayan Peso ($)', value: 'UYU' },
  { title: 'Uzbekistani Som (сўм)', value: 'UZS' },
  { title: 'Vanuatu Vatu (VT)', value: 'VUV' },
  { title: 'Venezuelan Bolívar Soberano (Bs.S)', value: 'VES' },
  { title: 'Vietnamese Dong (₫)', value: 'VND' },
  { title: 'Yemeni Rial (﷼)', value: 'YER' },
  { title: 'Zambian Kwacha (ZK)', value: 'ZMW' },
  { title: 'Zimbabwean Dollar ($)', value: 'ZWL' },
];

export const debtTypesOpt = [
  'Credit Card Debt',
  'Mortgage',
  'Auto Loan',
  'Student Loan',
  'Personal Loan',
  'Medical Debt',
  'Home Equity Loan',
  'Business Loan',
  'Payday Loan',
  'Tax Debt',
  'Credit Line',
  'Retail Store Credit',
  'Family Loan',
  'Peer-to-Peer Loan',
  'Consolidation Loan',
  'Installment Loan',
  'Secured Loan',
  'Unsecured Loan',
  'Overdraft',
  'Lease Agreement',
  'Timeshare Loan',
  'Boat Loan',
  'RV Loan',
  'Motorcycle Loan',
  'Construction Loan',
  'Bridge Loan',
  'Balloon Payment Loan',
  'Refinanced Loan',
  'Judgment Lien',
  'Cosigned Loan',
  'Other',
];

export const assetTypesOpt = [
  'Real Estate',
  'Stocks',
  'Bonds',
  'Mutual Funds',
  'ETFs',
  'Savings Accounts',
  'Certificates of Deposit',
  'Retirement Accounts (401k, IRA)',
  'Vehicles',
  'Jewelry',
  'Art',
  'Collectibles',
  'Business Ownership',
  'Intellectual Property',
  'Precious Metals',
  'Cryptocurrencies',
  'Life Insurance Policies',
  'Annuities',
  'Treasury Securities',
  'Commodities',
  'Peer-to-Peer Lending',
  'Foreign Currency',
  'Rental Properties',
  'Equipment',
  'Livestock',
  'Other',
];

export const expenseCategoriesOpt = [
  'Housing',
  'Utilities',
  'Food',
  'Transportation',
  'Healthcare',
  'Insurance',
  'Debt Payments',
  'Entertainment',
  'Education',
  'Childcare',
  'Groceries',
  'Dining Out',
  'Clothing',
  'Personal Care',
  'Household Supplies',
  'Subscriptions',
  'Gifts',
  'Donations',
  'Vacation/Travel',
  'Hobbies',
  'Pets',
  'Home Maintenance',
  'Auto Expenses',
  'Gym Membership',
  'Cell Phone',
  'Internet',
  'Cable/Streaming',
  'Credit Card Payments',
  'Student Loans',
  'Other',
];

export const incomeSourceOpt = [
  'Salary',
  'Investments',
  'Rental Income',
  'Business Income',
  'Pension',
  'Social Security',
  'Disability Benefits',
  'Unemployment Benefits',
  'Child Support',
  'Alimony',
  'Inheritance',
  'Lottery Winnings',
  'Royalties',
  'Freelance Work',
  'Consulting Fees',
  'Interest Income',
  'Dividend Income',
  'Capital Gains',
  'Annuity Payments',
  'Other Income',
];

export const investmentOpt = [
  'Stocks',
  'Bonds',
  'Mutual Funds',
  'ETFs',
  'Real Estate',
  'Commodities',
  'Cryptocurrencies',
  'Socially Responsible Investing (SRI)',
  'Index Funds',
  'Hedge Funds',
  'Private Equity',
  'Venture Capital',
  'Peer-to-Peer Lending',
  'Forex',
  'Options',
  'Futures',
  'Precious Metals',
  'Art and Collectibles',
  'Startups',
  'Green/Sustainable Investments',
];

export const investmentRestrictionOpt = [
  'Tobacco Industry',
  'Alcohol Industry',
  'Gambling Industry',
  'Weapons and Defense Industry',
  'Adult Entertainment Industry',
  'Fossil Fuel Industry',
  'Nuclear Energy',
  'Genetically Modified Organisms (GMOs)',
  'Animal Testing',
  'Deforestation',
  'Child Labor',
  'Sweatshops',
  'Human Rights Violations',
  'Oppressive Regimes',
  'Environmental Pollution',
  'Palm Oil Production',
  'Pesticides and Harmful Chemicals',
  'Factory Farming',
  'Fur Trade',
  'Conflict Minerals',
  'Predatory Lending',
  'Cryptocurrency',
  'Companies with Poor Labor Practices',
  'Non-Renewable Energy Sources',
  'Companies with Excessive Executive Compensation',
  'Companies with Poor Corporate Governance',
  'Companies Involved in Data Privacy Concerns',
  'Companies with Poor Diversity and Inclusion Practices',
  'Companies Involved in Political Lobbying',
  'Companies with High Carbon Footprint',
];

export const insuranceCoverageOpt = [
  'Life Insurance',
  'Health Insurance',
  'Disability Insurance',
  'Long-Term Care Insurance',
  'Property/Casualty Insurance (Home, Auto)',
  'Umbrella Insurance',
  'Dental Insurance',
  'Vision Insurance',
  'Critical Illness Insurance',
  'Accidental Death and Dismemberment Insurance',
  'Travel Insurance',
  'Pet Insurance',
  'Business Liability Insurance',
  'Professional Liability Insurance',
  'Cyber Insurance',
  'Flood Insurance',
  'Earthquake Insurance',
  'Renters Insurance',
  'Motorcycle Insurance',
  'Boat Insurance',
  'RV Insurance',
  'Identity Theft Insurance',
  'Cancer Insurance',
  'Mortgage Protection Insurance',
  'Gap Insurance',
  'Wedding Insurance',
  'Event Insurance',
  'Landlord Insurance',
  'Workers Compensation Insurance',
  'Directors and Officers Insurance',
];
